### PR TITLE
Adding bostrom

### PR DESCRIPTION
**Pull request by joeabbey**

### CODE REVIEW

**Comment by liangping** [comment]
Test Checkpoint: 
- [ ] Connect wallet, check if address is correct? 
- [ ] Transfer
- [ ] delegate/redelegate/unbond
- [ ] withdraw Validator's Commission
- [ ] withdraw Rewards

**Comment by joeabbey** [comment]
Hmmm it really should have chosen $BOOT as the token to delegate 

image

**Comment by joeabbey** [comment]
Another case where redelegate didn't behave as expected.

**Comment by liangping** [comment]
> Hmmm it really should have chosen $BOOT as the token to delegate

Yeah，good suggestion

**Comment by liangping** [comment]
> Another case where redelegate didn't behave as expected.

What's wrong?

**Comment by joeabbey-anchor** [comment]
> > Another case where redelegate didn't behave as expected.
> 
> 
> 
> What's wrong?
> 
> 

As far as I can tell the txn doesn't broadcast, which seems odd.

I'll take a look at the raw message in the morning.

**Comment by joeabbey-anchor** [comment]
Also amounts appear to be off by 10^6... 🤔

**Pull request merged**
