### PR TITLE
Patch - Uptime and Block pages improper display for version less than 0.45

### PR DESCRIPTION
**Pull request by effofxprime**
After the update to `fech.js` the `UPTIME` and `BLOCK` pages for Cosmos SDK versions below `0.45` were displaying as completely down in up time and not resolving monikers in the block page with the proposer.

I refactored the fetching blocks to return using ternary.  

Uptime(Including saved validator uptime) and Blocks added a version check, and if below `0.45` then convert the validator HEX address to BASE64, otherwise don't alter it and continue on.

I tested changes on Dev environment and my public hosted version.

Still needing to fix:
**My Validator Uptime**
Because it gets the config of the blockchain from the navigation, it will use that chains version for all.  Need to alter so that it figures out the version of the chain that is being monitored.

### CODE REVIEW

**Comment by effofxprime** [comment]
image

image

These images demonstrate the issue.  When on a chain below and when on a chain above v `0.45`

**Comment by effofxprime** [comment]
*unconfirmed*
State sync page seems to be affected as well.  The incorrect HASH is being displayed.  IE: LUM network.
Current display:
```
trust_height = 4359000
trust_hash = "d40df803c0750ba0f7039f7c0bcf42dc1df9076d76d4417ad7cf7ddc1d7ce3d17bec5e79e83dbaf00e82db4e85e40df9"
```

Actual hash of that block:
`1A34A8B1C6D3A598C89C3B35B2121EF618993B1849F77F556D268A6C206F5A35`

**Review by liangping — COMMENTED** [review]
Hello, Thanks for this patch, actually, these issue could be simpily fixed on fetch.js. 
So I am not going to accept this patch.

**Comment by effofxprime** [comment]
> Hello, Thanks for this patch, actually, these issue could be simpily fixed on fetch.js. So I am not going to accept this patch.

No problem.  Looking forward to seeing how it's fixed so I can learn a better way.  Thank you!

**Pull request closed without merging**
