### PR TITLE
Add Echelon

### PR DESCRIPTION
**Pull request by echelonfoundation**
Add Echelon (ECH) Blockchain

### CODE REVIEW

**Comment by liangping** [comment]
Hey, @echelonfoundation! Do you want to put your logo in here: `./public/logos/echolon.png` 
we have CDN for those statics files. thanks

**Comment by echelonfoundation** [comment]
@liangping We sure can, just found it more modular to link our github hosted one. We will update it now! Thank you!

**Comment by echelonfoundation** [comment]
@liangping We sure can, just found it more modular to link our github hosted one. We will update it now! Thank you!

**Comment by echelonfoundation** [comment]
@liangping Done! 🙏

**Comment by echelonfoundation** [comment]
@liangping Done! 🙏

**Review by liangping — APPROVED** [review]

**Comment by liangping** [comment]
Please invite more independent validators.

**Comment by echelonfoundation** [comment]
> Please invite more independent validators.



> Please invite more independent validators.

Yes we are working on a full launch soon, with many more validators coming online in the next few days, we will be hosting a presale also for a few early bird validators.

We would also like to donate a validator node worth of funds to you @liangping Let us know the best method of contact for you! (We have our Discord at: https://discord.gg/ArXNfK99ae)

**Comment by echelonfoundation** [comment]
> Please invite more independent validators.



> Please invite more independent validators.

Yes we are working on a full launch soon, with many more validators coming online in the next few days, we will be hosting a presale also for a few early bird validators.

We would also like to donate a validator node worth of funds to you @liangping Let us know the best method of contact for you! (We have our Discord at: https://discord.gg/ArXNfK99ae)

**Pull request merged**
