### PR TITLE
Adding chihuahua

### PR DESCRIPTION
**Pull request by joeabbey**
Added api.huahua.jabbey.io as the API endpoint.

### CODE REVIEW

**Comment by MercurySolar** [comment]
You can use our API if needed
https://chihuahua-api.mercury-nodes.net/

Also have rpc 
https://chihuahua-rpc.mercury-nodes.net/

**Comment by joeabbey** [comment]
Delegate / Undelegate worked but Redelegate didn't appear to commit to chain

**Comment by joeabbey** [comment]
Ah ha... well that would do it:

```
$ chihuahuad q tx 12B681AB13505DEDF849F42EFD15559FBB6F603A5720606404BE16C6A760F99F
code: 11
codespace: sdk
data: ""
gas_used: "200756"
gas_wanted: "200000"
height: "120563"
info: ""
logs: []
raw_log: 'out of gas in location: ReadFlat; gasWanted: 200000, gasUsed: 200756: out
  of gas'
timestamp: "2021-12-22T10:59:12Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "7000"
        denom: uhuahua
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_LEGACY_AMINO_JSON
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: Agn2TS3G99RaFqQ3qDSf2PEbLTgut6g1Jf44xTFd9YKu
      sequence: "12"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmos.staking.v1beta1.MsgBeginRedelegate
      amount:
        amount: "10000000"
        denom: uhuahua
      delegator_address: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
      validator_dst_address: chihuahuavaloper1xwazl8ftks4gn00y5x3c47auquc62ssu4ftf5w
      validator_src_address: chihuahuavaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4p40qac2
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - stsfLVHB/WQ59ADFbZ5Oxd3bRpScHq4G8U0rIh1cCEoLRTob8q1JxruCV+AZi2jbxo5ChQx4kGzy/lsFo1bLVQ==
txhash: 12B681AB13505DEDF849F42EFD15559FBB6F603A5720606404BE16C6A760F99F
```

**Comment by joeabbey** [comment]
Clicked `Advance` and Manually bumped to 300000 🎉 

```
$ chihuahuad q tx D6B70FF071D384019B657EBD60E749D1F7B66E3241DD4C59101B06BF5DD2BC09
code: 0
codespace: ""
data: 0A3B0A2A2F636F736D6F732E7374616B696E672E763162657461312E4D7367426567696E526564656C6567617465120D0A0B088ADF9F8F0610EB8DBA37
gas_used: "236761"
gas_wanted: "300000"
height: "120587"
info: ""
logs:
- events:
  - attributes:
    - key: receiver
      value: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
    - key: amount
      value: 129852uhuahua
    - key: receiver
      value: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
    - key: amount
      value: 100764uhuahua
    type: coin_received
  - attributes:
    - key: spender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: amount
      value: 129852uhuahua
    - key: spender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: amount
      value: 100764uhuahua
    type: coin_spent
  - attributes:
    - key: action
      value: /cosmos.staking.v1beta1.MsgBeginRedelegate
    - key: sender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: sender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: module
      value: staking
    - key: sender
      value: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
    type: message
  - attributes:
    - key: source_validator
      value: chihuahuavaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4p40qac2
    - key: destination_validator
      value: chihuahuavaloper1xwazl8ftks4gn00y5x3c47auquc62ssu4ftf5w
    - key: amount
      value: 10000000uhuahua
    - key: completion_time
      value: "2022-01-19T11:01:30Z"
    type: redelegate
  - attributes:
    - key: recipient
      value: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
    - key: sender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: amount
      value: 129852uhuahua
    - key: recipient
      value: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
    - key: sender
      value: chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga
    - key: amount
      value: 100764uhuahua
    type: transfer
  log: ""
  msg_index: 0
raw_log: '[{"events":[{"type":"coin_received","attributes":[{"key":"receiver","value":"chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss"},{"key":"amount","value":"129852uhuahua"},{"key":"receiver","value":"chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss"},{"key":"amount","value":"100764uhuahua"}]},{"type":"coin_spent","attributes":[{"key":"spender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"amount","value":"129852uhuahua"},{"key":"spender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"amount","value":"100764uhuahua"}]},{"type":"message","attributes":[{"key":"action","value":"/cosmos.staking.v1beta1.MsgBeginRedelegate"},{"key":"sender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"sender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"module","value":"staking"},{"key":"sender","value":"chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss"}]},{"type":"redelegate","attributes":[{"key":"source_validator","value":"chihuahuavaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4p40qac2"},{"key":"destination_validator","value":"chihuahuavaloper1xwazl8ftks4gn00y5x3c47auquc62ssu4ftf5w"},{"key":"amount","value":"10000000uhuahua"},{"key":"completion_time","value":"2022-01-19T11:01:30Z"}]},{"type":"transfer","attributes":[{"key":"recipient","value":"chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss"},{"key":"sender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"amount","value":"129852uhuahua"},{"key":"recipient","value":"chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss"},{"key":"sender","value":"chihuahua1jv65s3grqf6v6jl3dp4t6c9t9rk99cd8y2fjga"},{"key":"amount","value":"100764uhuahua"}]}]}]'
timestamp: "2021-12-22T11:01:30Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "10500"
        denom: uhuahua
      gas_limit: "300000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_LEGACY_AMINO_JSON
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: Agn2TS3G99RaFqQ3qDSf2PEbLTgut6g1Jf44xTFd9YKu
      sequence: "13"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmos.staking.v1beta1.MsgBeginRedelegate
      amount:
        amount: "10000000"
        denom: uhuahua
      delegator_address: chihuahua1l2ynn9djxrhwr968cwwhugrjugv482ns5856ss
      validator_dst_address: chihuahuavaloper1xwazl8ftks4gn00y5x3c47auquc62ssu4ftf5w
      validator_src_address: chihuahuavaloper1gp957czryfgyvxwn3tfnyy2f0t9g2p4p40qac2
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - wnXZyHCOql9SyZ4jXgGtU2iyqhd0taw3fXGezK9qzUZB4SN1lwyBnL3TW6NjRJYEnZGzcgY1Or4BkBZITs6V5w==
txhash: D6B70FF071D384019B657EBD60E749D1F7B66E3241DD4C59101B06BF5DD2BC09
```

**Pull request merged**
