### PR TITLE
TORI is on coingecko now

### PR DESCRIPTION
**Pull request by effofxprime**
https://www.coingecko.com/en/coins/teritori

TORI is listed on coingecko now.

### CODE REVIEW

**Review by liangping — COMMENTED** [review]
coingecko_id has moved into asset list.  This config here is deprecated.

**Comment by effofxprime** [comment]
> coingecko_id has moved into asset list. This config here is deprecated.

Where is this the asset list to update?

**Comment by liangping** [comment]
```json
  "assets": [
    {
      "base": "utori",
      "symbol": "TORI",
      "exponent": "6",
      "coingecko_id": "teritori",
      "logo": "/logos/teritori.svg"
    }
  ]
```

**Comment by effofxprime** [comment]
OHhh~!  I misunderstood and thought you meant a different file was holding that info.  Looks like it's good to go.  closing.

**Pull request closed without merging**
