### PR TITLE
fix jackal endpoints

### PR DESCRIPTION
**Pull request by PolkachuIntern**
Sorry for breaking it. This fixes it.

### CODE REVIEW

**Comment by liangping** [comment]
api format is wrong,  ["", ""], your is [" a, b"]

**Review by liangping — CHANGES_REQUESTED** [review]
shoud be ["https://api.jackalprotocol.com", "https://jackal-api.polkachu.com"]

**Comment by PolkachuIntern** [comment]
Terribly sorry about it. I was so confident that I did not run a local env test. This time I have run the app locally and confirm it works.

**Comment by liangping** [comment]
Don't worry, now I have a check robot which will check everything.

**Review by liangping — APPROVED** [review]

**Pull request merged**
