### PR TITLE
add polkachu endpoint for jackal

### PR DESCRIPTION
**Pull request by PolkachuIntern**

### CODE REVIEW

**Review by liangping — CHANGES_REQUESTED** [review]
Could you change the order or api, the official endpoints are not available.

**Comment by PolkachuIntern** [comment]
The chain is down right now, so none of the endpoints work. The chain will
start tomorrow and the official endpoints will work. If not, I will swap
positions.

**Comment by PolkachuIntern** [comment]
Okay. I have changed the order of API. please merge

**Comment by PolkachuIntern** [comment]
Confirmed that the team endpoints are working. Revert to the original PR so our endpoints are secondary to the team's endpoints.

**Comment by liangping** [comment]
@PolkachuIntern Hello, api and rpc should be array. please make a change.

**Comment by PolkachuIntern** [comment]
Sorry for breaking it. https://github.com/ping-pub/explorer/pull/244 fixes it

**Pull request merged**
